name: CICD

on:                                  
  push:
    branches: [main]

jobs:     
  CICD:                                
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login                  
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push Docker images              
        uses: docker/build-push-action@v5.3.0
        with:
          context: .   
          file: .     
          push: true    
          tags: |
            carlosmendesjmc/resultadonba:v1        
            carlosmendesjmc/resultadonba:latest     
            

     
