name: CICD

on:                                     # (on)é um gatilho, quando sempre que tiver um push na branche main sera execultado.
  push:
    branches: [main]

jobs:     
  CICD:                                 # nome da minha Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.5  # copia todos arquivos do seu repositorio para o executor da minha Pipeline
      
      - name: Docker Login With Config                  #Dockerlogin  credenciais na biblioteca
        uses: ximplez/docker-login-action@v1.0.0-beta
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push Docker images              #Docker build na biblioteca - Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: .    #define onde os arquivos estao alocados
          file: .       # o (.) indica que é o diretorio atual
          push: true    # empurra para o diretorio la no dockerhub
          tags: |
            carlosmendesjmc/resultadonba:v1         #v1 quer dizer primeira versão
            carlosmendesjmc/resultadonba:latest     # latest quer dizer ultima versão
            

     
