name: CICD

on:                                     # (on)é um gatilho, quando sempre que tiver um push na branche main sera execultado.
  push:
    branches: [main]

jobs:     
  CICD:                                 # nome da minha Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4.1.5  # copia todos arquivos do seu repositorio para o executor da minha Pipeline
      
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username:
          password:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
        
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run application
        run: |
          python app.py
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify JSON file
        run: |
          python -c "import json; json.load(open('results.json'))"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deployment
        run: echo "Deploying application..."
